events {
    worker_connections 1024;
}

http {
    upstream stock_market {
        server app1:8080;
        server app2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass         http://stock_market;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_connect_timeout 2s;   # max time to establish connection to backend
            proxy_read_timeout    10s;  # max time to wait for response from backend
            # retry na kolejną instancję TYLKO przy błędzie połączenia i TYLKO dla GET/HEAD
            proxy_next_upstream error timeout;
            proxy_next_upstream_tries 2;
        }
    }
}
